apiVersion: v2
name: paperless-ngx
description: Paperless-ngx Document Management
type: application
version: 0.1.0
appVersion: "2.5.0"
dependencies:
  - name: paperless-ngx
    version: 0.1.0        # Updated dependency version
    repository: https://rtomik.github.io/helm-charts
