apiVersion: v2
name: observability-stack
version: 1.0.0
dependencies:
  - name: kube-prometheus-stack
    version: 60.0.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: loki
    version: 5.43.0
    repository: https://grafana.github.io/helm-charts
  - name: alloy
    version: 0.2.0
    repository: https://grafana.github.io/helm-charts
