apiVersion: v2
name: nextcloud
description: Nextcloud Helm Chart Wrapper
type: application
version: 0.1.0
appVersion: "28.0.0"
dependencies:
  - name: nextcloud
    version: 6.6.0
    repository: https://nextcloud.github.io/helm/
